### ISSUE TITLE
Channels proposal/roadmap/checklist

### ISSUE THREAD

**Issue by 4w** [4w/exchat#1]
- [ ] Channels
    - [ ] operator permissions
        - [ ] mute players
        - [ ] kick players
        - [ ] set channel topic
        - [ ] nominate "moderators"
    - [ ] switching channels
    - [ ] persistent channels
        - [ ] default permissions set on joining
        - [ ] private channels with password
    - [ ] server-wide broadcast messages

#### Channels
Channels need some sort of information storage. [StorageRef (mod storage)](http://dev.minetest.net/StorageRef) could be used for that instead of a global storage table. This needs to set strings on channel creation and management and needs to get strings every time a player uses a channel-related command.

Prefixes (derived from IRC):
`#` - A channel, example: `#Lobby`
`##` - A private, unlisted channel, example: `##Private`
`@` - An operator of the current channel, example: `<@Username>`
`+` - A user having "voice" permission in a moderated channel, example: `<+Username>`
`.` - An administrator of the server (determined by permissions), example: `<.Username>`

Regular users do not have a prefix (`<Username>`). A prefix is colored in a special way so it can't be confused with a part of a nickname.

#### Operator permissions
Operators should be able to manage their channel. If an operator leaves a channel and comes back later the administrative permissions should be restored. All settings configured by the operator (channel topic, a description, bans, etc.) are stored in the mod storage.

#### Switching channels
The current channel will be stored as custom player attribute and will be read every time a player sends a non-private and non-technical chat message. Current channel from player attributes will be checked against the mod storage data and the message will be sent to all players that have the same channel set. This could be the bottleneck because every time someone sends a chat message all players on the server will be queried.

Channels will be joined, and there can always be only one active channel per user. Channels are joined using `/join #channelname`. users in the old channel get a message that a player left the channel and users in the new channel get a message that a player joined the channel. Channels can only be joined if not banned from the channel or when provided the correct password (`/join #passwordedchannel password`).

Channels will be automatically created when a player joins them and will be destroyed if the last player leaves the channel. When joining a non-existent channel the user will be made operator of the channel. 

#### Persistent channels
By default all users are sent to some kind of lobby. The lobby should be configurable in `settingtypes.txt` regarding name of the channel, channel topic, channel description and default permissions (for example set the channel to moderated but give voice to everyone so an operator can remove voice permissions from annoying players).

Other persistent channels should be created by server administrators only. They create the channel and grant operator permissions to the requester. Persistent channels keep all their configuration. Persistent channels can be used for server-wide community projects, special topics, administrative discussions (seecred and passworded), and so on.

#### Server-wide broadcasts
Server administrators should be able to send server-wide broadcasts to all of the players regardless in what channel they are to announce important information. Broadcasts are special formatted messages
